<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="keywords" content="大卫博士">
		<meta name="description" content="大卫博士，大卫博士护腰内裤">
		<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=0">
		<title>大卫博士官网</title>
		<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="/css/common.css" type="text/css">
		<link rel="stylesheet" href="/css/studio.css" type="text/css">
		<link rel="stylesheet" href="/css/experience.css" type="text/css">
		<link rel="stylesheet" href="/css/font.css" type="text/css">
		<link rel="stylesheet" href="/css/banner.css" type="text/css">
		<link rel="shortcut icon" href="/img/favicon.ico" type="Image/ico">
		<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=wDYEcxgRRheZwyC9jpN1Tt7fzr2zjosZ"></script>
		<script type="text/javascript" src="/js/jquery.min.js"></script>
	</head>
	<body>
		<div class="title"></div>
		<div class="container-fluid">
			<div class="nav">
				<div class="logo">
					<img src="/img/head-portrait.png">
				</div>
				<div class="nav_auto nav_list">
					<ul class="ul-nav" id="header_nav">
						<li ><a href="/index/index" class="actives">首页</a><span>|</span></li>
						<li><a href="/companyprofile/companyprofile">公司简介</a><span>|</span></li>
						<li><a href="/product/product" >产品系列</a><span>|</span></li>
						<li><a href="/school/school">微商学堂</a><span>|</span></li>
						<li><a href="/travel/travel">出国游玩</a><span>|</span></li>
						<li><a href="/customerfeedback/customerfeedback">顾客反馈</a><span>|</span></li>
						<li><a href="/companydynamic/companydynamic">公司动态</a><span>|</span></li>
						<li><a href="/contactus/contactus">联系我们</a></li>
					</ul>
				</div>
				<div class="nav_search">
					<input type="text" class="input_search"/>
					<input type="button" class="input_button"/>
					<img src="/img/search1.png" class="search">
				</div>
			</div>
		</div>
		<div class="link">
			<span>
				<a href="">首页</a>
				<span>></span>
			</span>
			<span>
				<a href="">线下门店</a>
				<span>></span>
			</span>
			<span style="color:#616161;font-size:12px;">
				体验店
			</span>
		</div>
		<div class="section">
			<div class="banner_opacity">
				<img src="/img/banner_opacity4.jpg" />
				<img src="/img/banner_opacity3.jpg"/>
				<img src="/img/banner_opacity2.jpg"/>
				<img src="/img/banner_opacity1.jpg"/>
				<i class="iconfont banner_left" title="上一页">&#xe601;</i>
				<i class="iconfont banner_right" title="下一页">&#xe600;</i>
			</div>
			<div class="address">
				<div class="address_container">
					<div class="address_select">
						<span>大卫博士授权工作室</span>
						<div class="select">
							<span class="province">请选择省份</span>
							<select style="width:204px;height:42px;line-height:42px;" class="province">
								<?php foreach($this->res as $key=>$val){?>
									<option >&nbsp;&nbsp;&nbsp;&nbsp;<?=$val['province']?></option>
								<?php }?>
							</select>
						</div>
						<div class="select">
							<span class="city">请选择城市</span>
							<select style="width:204px;height:42px;line-height:42px;" class="city">
								<?php foreach($this->city as $key=>$val){?>
									<option>&nbsp;&nbsp;&nbsp;&nbsp;<?=$val['city']?></option>
								<?php }?>
							</select>
						</div>
					</div>
					<ul class="addressList">
						<?php foreach($this->list as $key=>$val){?>
							<li>
								<p><?=$val['province']?><a><?=$val['experience_name']?></a></p>
								<p><?=$val['address']?></p>
								<p>电话：<?=$val['tel']?></p>
							</li>
						<?php }?>
					</ul>
				</div>
			</div>
			<div class="address" style="margin-top:35px;">
				<div class="address_container" style="padding-top:35px;">
					<div class="address_select">
						<span style="font-size:16px;"><img src="/img/address.png"/><span id="city"><?=$this->res[0]['province']?></span>共有<span id="city_nums"> <?=sizeof($this->list)?></span>家大卫博士线下体验店</span>
						<div class="select" style="float:right;">
							<span class="city">请选择城市</span>
							<select style="width:204px;height:42px;line-height:42px;" class="city">
								<?php foreach($this->city as $key=>$val){?>
									<option>&nbsp;&nbsp;&nbsp;&nbsp;<?=$val['city']?></option>
								<?php }?>
							</select>
						</div>
						<div class="select" style="float:right;">
							<span class="province">请选择省份</span>
							<select style="width:204px;height:42px;line-height:42px;" class="province">
								<?php foreach($this->res as $key=>$val){?>
									<option >&nbsp;&nbsp;&nbsp;&nbsp;<?=$val['province']?></option>
								<?php }?>
							</select>
						</div>
					</div>
				</div>
			</div>
			<div class="map_container">
				<div class="map_container_left" style="width: 325px;">
					<div class="address" style="margin-top:0px;">
						<div class="address_container" id="type">
							<div class="address_select" style="height:52px;border-bottom:1px solid #f5f5f5;">
								<span style="font-size:14px;">体验店查询</span>
								<div class="searchs" id="ie1">
									<input type="text" placeholder="请输入要查询的城市名" class="input_search" id="ie2"/>
									<span id="ie5" style="display:none;position:absolute;top:-18px;left:16px;color:grey;">请输入要查询到城市名</span>
									<div class="input_button" id="ie3"></div>
									<img src="/img/search1.png" class="search" id="ie4">
								</div>
							</div>
						</div>
					</div>
					<ul>
						<?php foreach($this->limit as $key=>$val){?>
							<li>
								<div class="top"><span>授权体验店</span></div>
								<div class="serial"><?=$key+1?></div>
								<div class="text">
									<p class="detailed_title">
										<b class="tel" coordinates=<?=$val['coordinates']?>>
											<span><?=$val['micro_letter_name']?></span> 
											<?=$val['tel']?>
										</b>
										<?=$val['experience_name']?>
										<span style="display:none;" id="city_none">
											<?=$val['city']?>店
										</span>
									</p>
									<p class="detailed_address"><?=$val['address']?></p>
								</div>
							</li>
						<?php }?>
					</ul>
					<p class="page">
						<a href="javascript:;" id="prev"><i class="iconfont banner_left">&#xe601;</i></a>
						<a href="javascript:;" id="next"><i class="iconfont banner_right">&#xe600;</i></a>
						<span><span id="nowPage">1</span>/<span id="sumPage"><?=ceil($this->counts/5)?></span></span>
					</p>
				</div>
				<div style="width:780px;height:520px;border:#ccc solid 1px;float:left;margin-left:20px;" id="dituContent"></div>
			</div>
			<div class="studio">
				<h2>大卫博士——线下授权工作室</h2>
				<p>大卫博士线下授权工作室是大卫博士有限公司和用户面对面的一个重要平台和窗口</p>
				<ul>
					<li>
						<img src="/img/studio1.png"/>
						<span class="title">最全面的咨询服务</span>
						<span>在大卫博士授权工作室,您可以获取关于大微博产品最全面的产品信息。无论是产品规格还是企业文化,甚至咨询合作,大卫博士授权工作室负责人都乐意为您耐心的解答</span>
					</li>
					<li>
						<img src="/img/studio1.png"/>
						<span class="title">最全面的咨询服务</span>
						<span>在大卫博士授权工作室,您可以获取关于大微博产品最全面的产品信息。无论是产品规格还是企业文化,甚至咨询合作,大卫博士授权工作室负责人都乐意为您耐心的解答</span>
					</li>
					<li>
						<img src="/img/studio1.png"/>
						<span class="title">最全面的咨询服务</span>
						<span>在大卫博士授权工作室,您可以获取关于大微博产品最全面的产品信息。无论是产品规格还是企业文化,甚至咨询合作,大卫博士授权工作室负责人都乐意为您耐心的解答</span>
					</li>
				</ul>
			</div>
			<div class="header-banner" style="margin-top:35px;">
				<ul class="hind-banner">
					<a href=""><img src="/img/ipad-banner4.jpg"/></a>
					<a href=""><img src="/img/ipad-banner1.jpg"/></a>
					<a href=""><img src="/img/ipad-banner2.jpg"/></a>
					<a href=""><img src="/img/ipad-banner3.jpg"/></a>
					<a href=""><img src="/img/ipad-banner4.jpg"/></a>
					<a href=""><img src="/img/ipad-banner1.jpg"/></a>
				</ul>
				<ul class="banner-circle">
					<li><img src="/img/banner-circle1.png"></li>
					<li><img src="/img/banner-circle2.png"></li>
					<li><img src="/img/banner-circle2.png"></li>
					<li><img src="/img/banner-circle2.png"></li>
				</ul>
				<img class="left display" src="/img/left.png"/>
				<img class="right display" src="/img/right.png"/>
			</div>
		</div>
		<div class="footer">
			<div class="nav">
				<div class="nav_auto">
					<ul class="ul-nav" id="footer_nav">
						<li><a href="">客服电话：400-6867733</a><span>|</span></li>
						<li><a href="">微信订阅号：大卫博士官方</a><span>|</span></li>
						<li><a href="">微信服务号：大卫博士</a><span>|</span></li>
						<li><a href="">用户：30-366天内不满意可退货</a><span>|</span></li>
						<li><a href="">代理：3个月后可退货退款</a></li>
					</ul>
				</div>
			</div>
			<div class="foot">
					<div class="footList_left footList_left_first">
						企业文化
					</div>
					<div class="footList_right">
						<p><a href=""><span>愿景</span></a></p>
						<p><a href=""><span>使命</span></a></p>
						<p class="lastP"><a href=""><span>价值观</span></a></p>
					</div>
					<div class="footList_left">
						线下门店
					</div>
					<div class="footList_right">
						<p><a href="/studio/studio"><span>工作室</span></a></p>
						<p class="lastP"><a href="/experience/experience"><span>体验店</span></a></p>
					</div>
					<div class="footList_left">
						公司历程
					</div>
					<div class="footList_right">
						<p><a href=""><span>大事件</span></a></p>
						<p class="lastP"><a href=""><span>产品优化历程</span></a></p>
					</div>
					<div class="footList_left">
						公司环境
					</div>
					<div class="footList_right">
						<p><a href=""><span>形象墙</span></a></p>
						<p><a href=""><span>荣誉墙</span></a></p>
						<p><a href=""><span>办公大厅</span></a></p>
						<p class="lastP"><a href=""><span>仓库展示</span></a></p>
					</div>
					<div class="footList_left">
						员工风采
					</div>
					<div class="footList_right">
						<p><a href=""><span>上课学习</span></a></p>
						<p><a href=""><span>拓展旅游</span></a></p>
						<p><a href=""><span>聚餐唱歌</span></a></p>
						<p class="lastP"><a href=""><span>健身娱乐</span></a></p>
					</div>
					<div class="footList_left">
						视频展示
					</div>
					<div class="footList_right">
						<p><a href=""><span>形象宣传</span></a><a href=""><span class="lastS">央视广告</span></a></p>
						<p><a href=""><span>内裤工匠</span></a><a href=""><span class="lastS">媒体采访</span></a></p>
						<p><a href=""><span>匠心之路</span></a><a href=""><span class="lastS">争霸视频</span></a></p>
						<p class="lastP"><a href=""><span>微商心法</span></a><a href=""><span class="lastS">精彩瞬间</span></a></p>
					</div>
			</div>
		</div>
		<div class="bottom">
			<img src="/img/head-portrait.png" class="bottom_left">
			<div class="bottom_center">
				<div class="nav" id="bottom_nav">
					<div class="nav_auto">
						<ul class="ul-nav" >
							<li ><a href="">首页</a><span>|</span></li>
							<li><a href="">公司简介</a><span>|</span></li>
							<li><a href="">产品系列</a><span>|</span></li>
							<li><a href="">微商学堂</a><span>|</span></li>
							<li><a href="">出国游玩</a><span>|</span></li>
							<li><a href="">顾客反馈</a><span>|</span></li>
							<li><a href="">公司动态</a><span>|</span></li>
							<li><a href="">联系我们</a></li>
						</ul>
					</div>
				</div>
				<p class="bottom_center_text">
					© mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2017]1530-131号 
					（京）网械平台备字（2018）第00005号 互联网药品信息服务资格证 (京) -非经营性-2014-0090 营业执照 医疗器械公告 
					违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试
				</p>
			</div>
			<div class="bottom_right">
				<img src="/img/truste.png">
				<img src="/img/v-logo-1.png">
				<img src="/img/v-logo-2.png">
				<img src="/img/v-logo-3.png">
				<img src="/img/v-logo-4.png">
			</div>
			<p class="bottom_bottom"></p>
		</div>
		<script src="/js/common.js" type="text/javascript"></script>
		<script src="/js/banner.js" type="text/javascript"></script>
		<script src="/js/ajax.js" type="text/javascript"></script>
		<script src="/js/studio.js" type="text/javascript"></script>
		<script src="/js/experience.js" type="text/javascript"></script>
		<script type="text/javascript">
			var selectProvince=$("div.address>div.address_container>div.address_select>div.select>select.province");
			var selectCity=$("div.address>div.address_container>div.address_select>div.select>select.city");
			var spanProvince=$("div.address>div.address_container>div.address_select>div.select>span.province");
			var spanCity=$("div.address>div.address_container>div.address_select>div.select>span.city");
			ajax(selectProvince,selectCity,spanProvince,spanCity,"experience");
		</script>
	</body>
</html>