<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="keywords" content="大卫博士">
		<meta name="description" content="大卫博士，大卫博士护腰内裤">
		<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=0">
		<title>大卫博士官网</title>
		<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="/css/common.css" type="text/css">
		<link rel="stylesheet" href="/css/studio.css" type="text/css">
		<link rel="stylesheet" href="/css/font.css" type="text/css">
		<link rel="stylesheet" href="/css/banner.css">
		<link rel="shortcut icon" href="/img/favicon.ico" type="Image/ico">
	</head>
	<body>
		<div class="title"></div>
		<div class="container-fluid">
			<div class="nav">
				<div class="logo">
					<img src="/img/head-portrait.png">
				</div>
				<div class="nav_auto nav_list">
					<ul class="ul-nav" id="header_nav">
						<li ><a href="/index/index" class="actives">首页</a><span>|</span></li>
						<li><a href="/companyprofile/companyprofile">公司简介</a><span>|</span></li>
						<li><a href="/product/product" >产品系列</a><span>|</span></li>
						<li><a href="/school/school">微商学堂</a><span>|</span></li>
						<li><a href="/travel/travel">出国游玩</a><span>|</span></li>
						<li><a href="/customerfeedback/customerfeedback">顾客反馈</a><span>|</span></li>
						<li><a href="/companydynamic/companydynamic">公司动态</a><span>|</span></li>
						<li><a href="/contactus/contactus">联系我们</a></li>
					</ul>
				</div>
				<div class="nav_search">
					<input type="text" class="input_search"/>
					<input type="button" class="input_button"/>
					<img src="/img/search1.png" id="search">
				</div>
			</div>
		</div>
		<div class="link">
			<span>
				<a href="">首页</a>
				<span>></span>
			</span>
			<span>
				<a href="">线下门店</a>
				<span>></span>
			</span>
			<span style="color:#616161;font-size:12px;">
				工作室
			</span>
		</div>
		<div class="section">
			<div class="banner_opacity">
				<img src="/img/banner_opacity4.jpg" />
				<img src="/img/banner_opacity3.jpg"/>
				<img src="/img/banner_opacity2.jpg"/>
				<img src="/img/banner_opacity1.jpg"/>
				<i class="iconfont banner_left" title="上一页">&#xe601;</i>
				<i class="iconfont banner_right" title="下一页">&#xe600;</i>
			</div>
			<div class="address">
				<div class="address_container">
					<div class="address_select">
						<span>大卫博士授权工作室</span>
						<div class="select">
							<span>请选择省份</span>
							<select style="width:204px;height:42px;line-height:42px;">
								<option selected>&nbsp;&nbsp;&nbsp;&nbsp;北京市</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;上海市</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;重庆市</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;天津市</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;河北省</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;山东省</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;辽宁省</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;黑龙江省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;吉林省</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;甘肃省</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;青海省</option>
								<option >&nbsp;&nbsp;&nbsp;&nbsp;河南省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;江苏省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;湖北省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;湖南省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;江西省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;浙江省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;广东省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;云南省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;福建省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;海南省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;山西省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;四川省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;陕西省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;贵州省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;安徽省</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;广西壮族自治区</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;内蒙古自治区</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;西藏自治区</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;新疆维吾尔自治区</option>
								<option>&nbsp;&nbsp;&nbsp;&nbsp;宁夏回族自治区</option>
							</select>
						</div>
						<div class="select">
							<span>请选择城市</span>
							<select style="width:204px;height:42px;line-height:42px;">
								<option selected>&nbsp;&nbsp;&nbsp;&nbsp;北京市</option>
							</select>
						</div>
					</div>
					<ul class="addressList">
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
						<li>
							<p>河南<a>大卫博士濮阳市授权体验店</a></p>
							<p>河南省濮阳市华龙区中华大道中华大道中华大道中华大道中华大道中华大道中华大道</p>
							<p>电话：0371-1234567 18625588667</p>
						</li>
					</ul>
				</div>
			</div>
			<div class="studio">
				<h2>大卫博士——线下授权工作室</h2>
				<p>大卫博士线下授权工作室是大卫博士有限公司和用户面对面的一个重要平台和窗口</p>
				<ul>
					<li>
						<img src="/img/studio1.png"/>
						<span class="title">最全面的咨询服务</span>
						<span>在大卫博士授权工作室,您可以获取关于大微博产品最全面的产品信息。无论是产品规格还是企业文化,甚至咨询合作,大卫博士授权工作室负责人都乐意为您耐心的解答</span>
					</li>
					<li>
						<img src="/img/studio1.png"/>
						<span class="title">最全面的咨询服务</span>
						<span>在大卫博士授权工作室,您可以获取关于大微博产品最全面的产品信息。无论是产品规格还是企业文化,甚至咨询合作,大卫博士授权工作室负责人都乐意为您耐心的解答</span>
					</li>
					<li>
						<img src="/img/studio1.png"/>
						<span class="title">最全面的咨询服务</span>
						<span>在大卫博士授权工作室,您可以获取关于大微博产品最全面的产品信息。无论是产品规格还是企业文化,甚至咨询合作,大卫博士授权工作室负责人都乐意为您耐心的解答</span>
					</li>
				</ul>
			</div>
			<div class="header-banner" style="margin-top:35px;">
				<ul class="hind-banner">
					<a href=""><img src="/img/ipad-banner4.jpg"/></a>
					<a href=""><img src="/img/ipad-banner1.jpg"/></a>
					<a href=""><img src="/img/ipad-banner2.jpg"/></a>
					<a href=""><img src="/img/ipad-banner3.jpg"/></a>
					<a href=""><img src="/img/ipad-banner4.jpg"/></a>
					<a href=""><img src="/img/ipad-banner1.jpg"/></a>
				</ul>
				<ul class="banner-circle">
					<li><img src="/img/banner-circle1.png"></li>
					<li><img src="/img/banner-circle2.png"></li>
					<li><img src="/img/banner-circle2.png"></li>
					<li><img src="/img/banner-circle2.png"></li>
				</ul>
				<img class="left display" src="/img/left.png"/>
				<img class="right display" src="/img/right.png"/>
			</div>
		</div>
		<div class="footer">
			<div class="nav">
				<div class="nav_auto">
					<ul class="ul-nav" id="footer_nav">
						<li><a href="">客服电话：400-6867733</a><span>|</span></li>
						<li><a href="">微信订阅号：大卫博士官方</a><span>|</span></li>
						<li><a href="">微信服务号：大卫博士</a><span>|</span></li>
						<li><a href="">用户：30-366天内不满意可退货</a><span>|</span></li>
						<li><a href="">代理：3个月后可退货退款</a></li>
					</ul>
				</div>
			</div>
			<div class="foot">
					<div class="footList_left footList_left_first">
						企业文化
					</div>
					<div class="footList_right">
						<p><a href=""><span>愿景</span></a></p>
						<p><a href=""><span>使命</span></a></p>
						<p class="lastP"><a href=""><span>价值观</span></a></p>
					</div>
					<div class="footList_left">
						线下门店
					</div>
					<div class="footList_right">
						<p><a href="/studio/studio"><span>工作室</span></a></p>
						<p class="lastP"><a href="/experience/experience"><span>体验店</span></a></p>
					</div>
					<div class="footList_left">
						公司历程
					</div>
					<div class="footList_right">
						<p><a href=""><span>大事件</span></a></p>
						<p class="lastP"><a href=""><span>产品优化历程</span></a></p>
					</div>
					<div class="footList_left">
						公司环境
					</div>
					<div class="footList_right">
						<p><a href=""><span>形象墙</span></a></p>
						<p><a href=""><span>荣誉墙</span></a></p>
						<p><a href=""><span>办公大厅</span></a></p>
						<p class="lastP"><a href=""><span>仓库展示</span></a></p>
					</div>
					<div class="footList_left">
						员工风采
					</div>
					<div class="footList_right">
						<p><a href=""><span>上课学习</span></a></p>
						<p><a href=""><span>拓展旅游</span></a></p>
						<p><a href=""><span>聚餐唱歌</span></a></p>
						<p class="lastP"><a href=""><span>健身娱乐</span></a></p>
					</div>
					<div class="footList_left">
						视频展示
					</div>
					<div class="footList_right">
						<p><a href=""><span>形象宣传</span></a><a href=""><span class="lastS">央视广告</span></a></p>
						<p><a href=""><span>内裤工匠</span></a><a href=""><span class="lastS">媒体采访</span></a></p>
						<p><a href=""><span>匠心之路</span></a><a href=""><span class="lastS">争霸视频</span></a></p>
						<p class="lastP"><a href=""><span>微商心法</span></a><a href=""><span class="lastS">精彩瞬间</span></a></p>
					</div>
			</div>
		</div>
		<div class="bottom">
			<img src="/img/head-portrait.png" class="bottom_left">
			<div class="bottom_center">
				<div class="nav" id="bottom_nav">
					<div class="nav_auto">
						<ul class="ul-nav" >
							<li ><a href="">首页</a><span>|</span></li>
							<li><a href="">公司简介</a><span>|</span></li>
							<li><a href="">产品系列</a><span>|</span></li>
							<li><a href="">微商学堂</a><span>|</span></li>
							<li><a href="">出国游玩</a><span>|</span></li>
							<li><a href="">顾客反馈</a><span>|</span></li>
							<li><a href="">公司动态</a><span>|</span></li>
							<li><a href="">联系我们</a></li>
						</ul>
					</div>
				</div>
				<p class="bottom_center_text">
					© mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2017]1530-131号 
					（京）网械平台备字（2018）第00005号 互联网药品信息服务资格证 (京) -非经营性-2014-0090 营业执照 医疗器械公告 
					违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试
				</p>
			</div>
			<div class="bottom_right">
				<img src="/img/truste.png">
				<img src="/img/v-logo-1.png">
				<img src="/img/v-logo-2.png">
				<img src="/img/v-logo-3.png">
				<img src="/img/v-logo-4.png">
			</div>
			<p class="bottom_bottom"></p>
		</div>
		<script src="/js/jquery.min.js" type="text/javascript"></script>
		<script src="/js/common.js" type="text/javascript"></script>
		<script src="/js/banner.js" type="text/javascript"></script>
		<script src="/js/studio.js" type="text/javascript"></script>
	</body>
</html>