<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="keywords" content="大卫博士">
		<meta name="description" content="大卫博士，大卫博士护腰内裤">
		<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=0">
		<title>大卫博士官网</title>
		<link rel="stylesheet" href="/css/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="/css/common.css" type="text/css">
		<link rel="stylesheet" href="/css/companydynamic.css" type="text/css">
		<link rel="shortcut icon" href="/img/favicon.ico" type="Image/ico">
	</head>
	<body>
		<div class="title"></div>
		<div class="container-fluid">
			<div class="nav">
				<div class="logo">
					<img src="/img/head-portrait.png">
				</div>
				<div class="nav_auto nav_list">
					<ul class="ul-nav" id="header_nav">
						<li ><a href="/index/index">首页</a><span>|</span></li>
						<li><a href="/companyprofile/companyprofile">公司简介</a><span>|</span></li>
						<li><a href="/product/product">产品系列</a><span>|</span></li>
						<li><a href="/school/school">微商学堂</a><span>|</span></li>
						<li><a href="/travel/travel">出国游玩</a><span>|</span></li>
						<li><a href="/customerfeedback/customerfeedback">顾客反馈</a><span>|</span></li>
						<li><a href="/companydynamic/companydynamic" class="actives">公司动态</a><span>|</span></li>
						<li><a href="/contactus/contactus">联系我们</a></li>
					</ul>
				</div>
				<div class="nav_search">
					<input type="text" class="input_search"/>
					<input type="button" class="input_button"/>
					<img src="/img/search1.png" class="search">
				</div>
			</div>
			
		</div>
		<div class="section">
			<a href="" >
				<div class="dynamicList">
					<img src="/img/dynamic1.jpg"/>
					<div class="dynamicList_right">
						<p>【行云流水】生活和身体让我吃尽了苦头，结缘了大卫博士苦尽甘来</p>
						<p class="time">2018年10月23日</p>
					</div>
				</div>
			</a>
			<a href="" >
				<div class="dynamicList">
					<img src="/img/dynamic1.jpg"/>
					<div class="dynamicList_right">
						<p>【行云流水】生活和身体让我吃尽了苦头，结缘了大卫博士苦尽甘来</p>
						<p class="time">2018年10月23日</p>
					</div>
				</div>
			</a>
			<a href="" >
				<div class="dynamicList">
					<img src="/img/dynamic1.jpg"/>
					<div class="dynamicList_right">
						<p>【行云流水】生活和身体让我吃尽了苦头，结缘了大卫博士苦尽甘来</p>
						<p class="time">2018年10月23日</p>
					</div>
				</div>
			</a>
			<a href="" >
				<div class="dynamicList">
					<img src="/img/dynamic1.jpg"/>
					<div class="dynamicList_right">
						<p>【行云流水】生活和身体让我吃尽了苦头，结缘了大卫博士苦尽甘来</p>
						<p class="time">2018年10月23日</p>
					</div>
				</div>
			</a>
			<a href="" >
				<div class="dynamicList none">
					<img src="/img/dynamic1.jpg"/>
					<div class="dynamicList_right">
						<p>【行云流水】生活和身体让我吃尽了苦头，结缘了大卫博士苦尽甘来</p>
						<p class="time">2018年10月23日</p>
					</div>
				</div>
			</a>
			<a href="" >
				<div class="dynamicList none">
					<img src="/img/dynamic1.jpg"/>
					<div class="dynamicList_right">
						<p>【行云流水】生活和身体让我吃尽了苦头，结缘了大卫博士苦尽甘来</p>
						<p class="time">2018年10月23日</p>
					</div>
				</div>
			</a>
			<div class="paging">
				<a href=""><span>首页</span></a>
				<a href=""><span>上一页</span></a>
				<a href=""><span class="active">1</span></a>
				<a href=""><span>2</span></a>
				<a href=""><span>3</span></a>
				<a href=""><span>4</span></a>
				<a href=""><span>5</span></a>
				<a href=""><span>下一页</span></a>
				<a href=""><span>末页</span></a>
			</div>
		</div>
		<div class="footer">
			<div class="nav">
				<div class="nav_auto">
					<ul class="ul-nav" id="footer_nav">
						<li><a href="">客服电话：400-6867733</a><span>|</span></li>
						<li><a href="">微信订阅号：大卫博士官方</a><span>|</span></li>
						<li><a href="">微信服务号：大卫博士</a><span>|</span></li>
						<li><a href="">用户：30-366天内不满意可退货</a><span>|</span></li>
						<li><a href="">代理：3个月后可退货退款</a></li>
					</ul>
				</div>
			</div>
			<div class="foot">
					<div class="footList_left footList_left_first">
						企业文化
					</div>
					<div class="footList_right">
						<p><a href=""><span>愿景</span></a></p>
						<p><a href=""><span>使命</span></a></p>
						<p class="lastP"><a href=""><span>价值观</span></a></p>
					</div>
					<div class="footList_left">
						线下门店
					</div>
					<div class="footList_right">
						<p><a href=""><span>工作室</span></a></p>
						<p class="lastP"><a href=""><span>体验店</span></a></p>
					</div>
					<div class="footList_left">
						公司历程
					</div>
					<div class="footList_right">
						<p><a href=""><span>大事件</span></a></p>
						<p class="lastP"><a href=""><span>产品优化历程</span></a></p>
					</div>
					<div class="footList_left">
						公司环境
					</div>
					<div class="footList_right">
						<p><a href=""><span>形象墙</span></a></p>
						<p><a href=""><span>荣誉墙</span></a></p>
						<p><a href=""><span>办公大厅</span></a></p>
						<p class="lastP"><a href=""><span>仓库展示</span></a></p>
					</div>
					<div class="footList_left">
						员工风采
					</div>
					<div class="footList_right">
						<p><a href=""><span>上课学习</span></a></p>
						<p><a href=""><span>拓展旅游</span></a></p>
						<p><a href=""><span>聚餐唱歌</span></a></p>
						<p class="lastP"><a href=""><span>健身娱乐</span></a></p>
					</div>
					<div class="footList_left">
						视频展示
					</div>
					<div class="footList_right">
						<p><a href=""><span>形象宣传</span></a><a href=""><span class="lastS">央视广告</span></a></p>
						<p><a href=""><span>内裤工匠</span></a><a href=""><span class="lastS">媒体采访</span></a></p>
						<p><a href=""><span>匠心之路</span></a><a href=""><span class="lastS">争霸视频</span></a></p>
						<p class="lastP"><a href=""><span>微商心法</span></a><a href=""><span class="lastS">精彩瞬间</span></a></p>
					</div>
			</div>
		</div>
		<div class="bottom">
			<img src="/img/head-portrait.png" class="bottom_left">
			<div class="bottom_center">
				<div class="nav" id="bottom_nav">
					<div class="nav_auto">
						<ul class="ul-nav" >
							<li ><a href="">首页</a><span>|</span></li>
							<li><a href="">公司简介</a><span>|</span></li>
							<li><a href="">产品系列</a><span>|</span></li>
							<li><a href="">微商学堂</a><span>|</span></li>
							<li><a href="">出国游玩</a><span>|</span></li>
							<li><a href="">顾客反馈</a><span>|</span></li>
							<li><a href="">公司动态</a><span>|</span></li>
							<li><a href="">联系我们</a></li>
						</ul>
					</div>
				</div>
				<p class="bottom_center_text">
					© mi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134号 京网文[2017]1530-131号 
					（京）网械平台备字（2018）第00005号 互联网药品信息服务资格证 (京) -非经营性-2014-0090 营业执照 医疗器械公告 
					违法和不良信息举报电话：185-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试
				</p>
			</div>
			<div class="bottom_right">
				<img src="/img/truste.png">
				<img src="/img/v-logo-1.png">
				<img src="/img/v-logo-2.png">
				<img src="/img/v-logo-3.png">
				<img src="/img/v-logo-4.png">
			</div>
			<p class="bottom_bottom"></p>
		</div>
		<script src="/js/jquery.min.js" type="text/javascript"></script>
		<script src="/js/common.js" type="text/javascript"></script>
		<script src="/js/companydynamic.js" type="text/javascript"></script>
	</body>
</html>